# Generated by Django 4.2.7 on 2024-01-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0003_firstbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
